library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(magrittr)
library(shiny)
library(bslib)
library(plotly)

base <- read_excel("datos/Base_Virrey.xlsx", 
                           sheet = "General")

# GINECOLOGIA -------------------------------------------------------------

#POMEROY

base$`CODIGO PROCEDIMIENTO 1`[base$`PROCEDIMIENTO 1`=="ABLACION U OCLUSION DE TROMPA DE FALOPIO BILATERAL POR LAPAROTOMIA"]<-"662010000"
base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`=="6622010000"]<-"662010000"
base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`=="6620100000"]<-"662010000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`=="662010000"]<-"ABLACION U OCLUSION DE TROMPA DE FALOPIO BILATERAL POR LAPAROTOMIA"

#LEGRADO
base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`=="6.90103e+16"]<-"6901030000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`=="6901030000"]<-"LEGRADO UTERINO GINECOLOGICO"

#ESCISION DE POLIPO EN CUELLO UTERINO (CERVIX)

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`=="6731010000"]<-"ESCISION DE POLIPO EN CUELLO UTERINO (CERVIX)"

#MKARSUPIALIZACION

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`=="712003000"]<-"MARSUPIALIZACION O DRENAJE EN LA GLANDULA DE BARTHOLIN"

# OFTALMOLOGIA ------------------------------------------------------------

#PTERIGIO

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "1.03104e+16"]<-"1031040000"
base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "10310400000"]<-"1031040000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "1031040000"]<-"RESECCION DE PTERIGION (NASAL O TEMPORAL) CON INJERTO"

#CHALAZION VIA ANTERIOR

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "821010100"]<-"RESECCION DE CHALAZION VIA ANTERIOR"

#CHALAZION VIA POSTERIOR

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "8210200000"]<-"821020000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "821020000"]<-"RESECCION DE CHALAZION VIA POSTERIOR"

#RESECCION DE TUMOR BENIGNO O MALIGNO DE PARPADO

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "823010000"]<-"RESECCION DE TUMOR BENIGNO O MALIGNO DE PARPADO, ESPESOR PARCIAL, UN TERCIO"

# OTORRINO ----------------------------------------------------------------

#TURBINOPLASTIA VIA TRANSNASAL

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "2193020000"]<-"TURBINOPLASTIA VIA TRANSNASAL"

#SEPTOPLASTIA PRIMARIA TRANSNASAL

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "2195010000"]<-"SEPTOPLASTIA PRIMARIA TRANSNASAL"


# CIRUGIA GENERAL ---------------------------------------------------------

#LIGADURA Y ESCISION DE VENAS VARICOSAS DE MIEMBROS INFERIORES

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "3889050000"]<-"LIGADURA Y ESCISION DE VENAS VARICOSAS DE MIEMBROS INFERIORES"

#HERNIORRAFIA INGUINAL

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "5300010000"]<-"HERNIORRAFIA INGUINAL UNILATERAL VIA ABIERTA"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "5310010000"]<-"HERNIORRAFIA INGUINAL BILATERAL VIA ABIERTA"

#HERNIORRAFIA UMBILICAL

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "5340010000"]<-"HERNIORRAFIA UMBILICAL VIA ABIERTA"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "5341010000"]<-"HERNIORRAFIA UMBILICAL REPRODUCIDA VIA ABIERTA"

#HERNIORRAFIA EPIGASTRICA

base$`CODIGO PROCEDIMIENTO 1`[base$`PROCEDIMIENTO 1`==
                                "HERNIORRAFIA EPIGASTRICA VIA ABIERTA"]<-"5352040100"
base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "5352010100"]<-"5352040100"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "5352040100"]<-"HERNIORRAFIA EPIGASTRICA VIA ABIERTA"

#RESECCION DE TUMOR BENIGNO EN LA PARED ABDOMINAL

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "5431010000"]<-"RESECCION DE TUMOR BENIGNO EN LA PARED ABDOMINAL VIA ABIERTA"

#EVENTRORRAFIA

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "54740300000"]<-"5474030000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "5474030000"]<-"EVENTRORRAFIA VIA ABIERTA"

#RESECCION DE TUMOR BENIGNO O MALIGNO

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8641010000"]<-"RESECCION DE TUMOR BENIGNO O MALIGNO HASTA TRES CENTIMETROS"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8641020000"]<-"RESECCION DE TUMOR BENIGNO O MALIGNO ENTRE TRES Y CINCO CENTIMETROS"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8641030000"]<-"RESECCION DE TUMOR BENIGNO O MALIGNO DE PIEL O TEJIDO CELULAR SUBCUTANEO AREA GENERAL, ENTRE CINCO A DIEZ CENTIMETROS"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8641040000"]<-"RESECCION DE TUMOR BENIGNO O MALIGNO DE PIEL O TEJIDO CELULAR SUBCUTANEO AREA GENERAL, DE MAS DE DIEZ CENTIMETROS"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8641050000"]<-"RESECCION DE TUMOR BENIGNO DE PIEL O TEJIDO CELULAR SUBCUTANEO AREA GENERAL, CON REPARACION (COLGAJO O INJERTO)"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8642020000"]<-"RESECCION DE TUMOR BENIGNO O MALIGNO DE PIEL O TEJIDO CELULAR SUBCUTANEO DE AREA ESPECIAL, ENTRE UNO A DOS CENTIMETROS"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8642030000"]<-"RESECCION DE TUMOR BENIGNO O MALIGNO DE PIEL O TEJIDO CELULAR SUBCUTANEO DE AREA ESPECIAL, ENTRE DOS A TRES CENTIMETROS"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8642040000"]<-"RESECCION DE TUMOR BENIGNO O MALIGNO DE PIEL O TEJIDO CELULAR SUBCUTANEO DE AREA ESPECIAL, ENTRE TRES A CINCO CENTIMETROS"

#COLGAJO LOCAL SIMPLE DE PIEL

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8672030000"]<-"8672020000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8670020000"]<-"COLGAJO LOCAL SIMPLE DE PIEL ENTRE DOS A CINCO CENTIMETROS CUADRADOS"

#COLGAJO LOCAL DE PIEL COMPUESTO

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8672020000"]<-"COLGAJO LOCAL DE PIEL COMPUESTO DE VECINDAD ENTRE DOS A CINCO CENTIMETROS CUADRADOS"

# UROLOGIA ----------------------------------------------------------------

#HIDROCELECTOMIA

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6.121e+09"]<-"REPARACION O ESCISION DE HIDROCELE (HIDROCELECTOMIA) DE TUNICA VAGINALIS SOD"

#Espermatocelectomia

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6.321e+09"]<-"ESPERMATOCELECTOMIA O RESECCION QUISTE DEL EPIDIDIMO SOD"

#VASECTOMIA

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6.373e+09"]<-"VASECTOMIA SOD"

#FULGURTACION O RESECCION DE LESION EN PENE

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6.421e+09"]<-"FULGURTACION O RESECCION DE LESION EN PENE"

#CIRCUNSICION

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "6.4e+10"]<-"6.4e+09"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6.4e+09"]<-"CIRCUNSICION SOD"

#ORQUIECTOMIA

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6230010000"]<-"ORQUIECTOMIA CON EPIDIDIDECTOMIA (RADICAL)"

#FIJACION TESTICULAR

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6251040000"]<-"FIJACION TESTICULAR"

#VARICOCELECTOMIA

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6310100000"]<-"VARICOCELECTOMIA CON LIGADURA ALTA DE VENA ESPERMATICA"

#PLASTIA DE FRENILLO

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "644920000"]<-"6449200000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "6449200000"]<-"PLASTIA DE FRENILLO PENEAL"

# CIRUGIA PLASTICA --------------------------------------------------------

#RESECCION DE LESION DE MAMA

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "8.621e+09"]<-"8.521e+09"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8.521e+09"]<-"RESECCION LOCAL DE LESION DE MAMA SOD"

#RESECCION DE TUMOR BENIGNO

base$`CODIGO PROCEDIMIENTO 1`[base$`PROCEDIMIENTO 1`==
                                "RESECCION DE TUMOR BENIGNO O MALIGNO DE PIEL O TEJIDO CELULAR SUBCUTANEO DE AREA ESPECIAL, ENTRE DOS A TRES CENTIMETROS"]<-"8642030000"

#BIOPSIA DEPIEL CON SACABOCADO Y SUTURA SIMPLE

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "8601020000"]<-"8601010000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8601010000"]<-"BIOPSIA DEPIEL CON SACABOCADO Y SUTURA SIMPLE"
base$`PROCEDIMIENTO 1`[base$`PROCEDIMIENTO 1`==
                         "BIOPSIA DEPIEL CON SACABOCADO Y SUTURA SIMPLE"]<-
                          "BIOPSIA DE PIEL CON SACABOCADO Y SUTURA SIMPLE"

#EXTRACCION DE CUERPO EXTRAÑO EN PIEL O TEJIDO CELULAR SUBCUTANEO DE AREA GENERAL POR INCISION

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "8612010000"]<-"8612020000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8612020000"]<-"EXTRACCION DE CUERPO EXTRAÑO EN PIEL O TEJIDO CELULAR SUBCUTANEO DE AREA GENERAL POR INCISION"

#INFILTRACION INTRALESIONAL CON MEDICAMENTO HASTA DE CINCO LESIONES

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8614010000"]<-"INFILTRACION INTRALESIONAL CON MEDICAMENTO HASTA DE CINCO LESIONES"

#RESECCION QUISTE PILONIDAL

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8621030000"]<-"RESECCION QUISTE PILONIDAL (CIERRE PARCIAL O ESCISION ABIERTA)"

# ORTOPEDIA ---------------------------------------------------------------

#DESCOMPRESION DE NERVIO EN TUNEL DEL CARPO

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "443030000"]<-"DESCOMPRESION DE NERVIO EN TUNEL DEL CARPO VIA ABIERTA"
base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "4430400000"]<-"443040000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "443040000"]<-"DESCOMPRESION DE NERVIO EN TUNEL DEL CARPO CON NEUROLISIS VIA ABIERTA"

#RESECCION DE GANGLION DORSAL DE MUÑECA

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "82210400"]<-"8221040000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8221040000"]<-"RESECCION DE GANGLION DORSAL DE MUÑECA VIA ABIERTA"

#RESECCION DE GANGLION PALMAR DE MUÑECA

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "8.22106e+16"]<-"8221060000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8221060000"]<-"RESECCION DE GANGLION PALMAR DE MUÑECA VIA ABIERTA"

#CORRECCION QUIRURGICA DE DEDO EN GATILLO (DEDO DE RESORTE)

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "8284010000"]<-"8284040000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8284040000"]<-"CORRECCION QUIRURGICA DE DEDO EN GATILLO (DEDO DE RESORTE)"

#ESCISION DE GANGLION DE ENVOLTURA DE TENDON, EXCEPTO DE MANO

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8331010000"]<-"ESCISION DE GANGLION DE ENVOLTURA DE TENDON, EXCEPTO DE MANO"

#MATRICECTOMIA

base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8627020000"]<-"MATRICECTOMIA PARCIAL"
base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "862730000"]<-"8627030000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8627030000"]<-"MATRICECTOMIA TOTAL"

#EXTRACCION DE DISPOSITIVO IMPLANTADO

base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "7863010000"]<-"7867010000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "7867010000"]<-"EXTRACCION DE DISPOSITIVO IMPLANTADO EN TIBIA O PERONE"

# DERMATOLOGIA ------------------------------------------------------------

#RESECCION DE LESION DE LESIONES CUTANEAS 
base$`CODIGO PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                                "8631040000"]<-"8631030000"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8631030000"]<-"RESECCION DE LESIONES CUTANEAS POR CAUTERIZACION"
base$`PROCEDIMIENTO 1`[base$`CODIGO PROCEDIMIENTO 1`==
                         "8631050000"]<-"RESECCION DE LESIONES CUTANEAS POR CAUTERIZACION FULGURACION O CRIOTERAPIA"

base$`ESPECIALIDAD TRATANTE`[base$`CIRUJANO TRATANTE`==
                               "PINEDA ALZATE CARLOS ALBERTO"]<-"OFTALMOLOGIA"
base$`ESPECIALIDAD TRATANTE`[base$`CIRUJANO TRATANTE`==
                               "CABRERA QUECANO ANDRES GUILLERMO"]<-"DERMATOLOGIA"
base$`ESPECIALIDAD TRATANTE`[base$`CIRUJANO TRATANTE`==
                               "ARIZA MAESTRE SHIRLEY DAYANA"]<-"DERMATOLOGIA"
base$`CIRUJANO TRATANTE`[base$`CIRUJANO TRATANTE`==
                           "MONTOYA PALACIOS GLORIA MARIA"]<-"MONTOYA PALACIO GLORIA MARIA"

colnames(base)[25]<-"CAUSA DE CANCELACION"

quitar_na<-function(x){ifelse(is.na(x),"NO",x)}

base$CANCELACION<-quitar_na(base$CANCELACION)

base$`FECHA DE CIRUGIA`<-as.Date(base$`FECHA DE CIRUGIA`)

proc_o<-base %>% select(`PROCEDIMIENTO 1`) %>% filter(`PROCEDIMIENTO 1`!="NA") %>% unique()

proc<-c("LEGRADO","H. INGUINAL","POMEROY","PTERIGION","RTB-A.ESPECIAL.3-5CM",
        "AMIGDALECTOMIA","EXTRACCION CUERPO E.","VASECTOMIA","RTB-A.ESPECIAL 1-2CM",
        "GANGLION EN DEDOS","RTB-A.GENERAL 5-10CM","MARSUPIALIZACIÓN",
        "PLASTIA DE FRENILLO","CIRCUNSICION","H. UMBILICAL","RTB-A.GENERAL 3-5CM",
        "SEPTOPLASTIA","TURBINOPLASTIA","HIDROCELECTOMIA","H. EPIGASTRICA",
        "DESCOMPRESION TUNEL + NEUROLISIS","GANGLION MUÑECA","CHALAZION POSTERIOR",
        "VARICOCELECTOMIA","RTB + REPARACION","VARICECTOMIA","RTB-A.GENERAL < 3CM",
        "CISTOSCOPIA","SEPTORRINOPLASTIA","EXTRACCION CUERPO EXTRAÑO","RTB TRANSNASAL",
        "BIOPSIA DE PIEL","RESECCION DE LESIONES CUTANEAS","DEDO EN GATILLO",
        "RTB PARPADO 1/3","RTM PIEL","CAUTERIZACION LESIONES CUTANEAS",
        "FULGURACION LESION EN PENE","FIJACION TESTICULAR","EVENTRORRAFIA","H. UMBILICAL REPRODUCIDA",
        "GANGLION PALMAR","RTB-A.ESPECIAL 2-3CM","RESECCION LESION EN CONJUNTIVA",
        "COLGAJO LOCAL SIMPLE 2-5CM^2","RESECCION DE QUISTE PILONIDAL",
        "RTB-A.ESPECIAL > 5CM","GINECOMASTIA","RTB-A.GENERAL > 10CM",
        "TRATAMIENTO ODONTOLOGICO","H. INGUINAL BILATERAL","RTB PARPADO 2/3",
        "ESCISION POLIPO CUELLO UTERINO","EXTRACCION DISPOSITIVO TIBIA O PERONE",
        "H. INGUINAL REPRODUCIDA","RTB PARED ABDOMINAL","ESPERMATOCELECTOMIA",
        "MATRICECTOMIA TOTAL","DESCOMPRESION TUNEL","RESECCION DE CICATRIZ HIPERTROFICA A. ESPECIAL",
        "COLGAJO SIMPLE LOCAL SIMPLE 5-10CM^2","COLGAJO LOCAL COMPUESTO 2-5CM^2",
        "MATRICECTOMIA PARCIAL","INFILTRACION INTRALESIONAL 5-10 LESIONES",
        "SOPORTE ANESTESICO PARA CONSULTA","ORQUIECTOMIA","GANGLION ENVOLTURA DE TENDON",
        "INFILTRACION INTRALESIONAL <5 LESIONES", "CHALAZION VIA ANTERIOR",
        "RESECCION SIMPLE DE CICATRIZ A.ESPECIAL","RESECCION QUISTE SEBACEO EN ESCROTO",
        "EVENTRORRAFIA + MALLA")

cambio<- data.frame(proc_o,proc)
for (x in 1:72) {
base$`PROCEDIMIENTO 1`[[x]]<-base$`PROCEDIMIENTO 1`[base$`PROCEDIMIENTO 1`==cambio[x, 1]]<-cambio[x, 2]  
}


base<- 
  base %>%
  select(`FECHA DE CIRUGIA`,
         `SALA DE CIRUGIA`,
         (EDAD:`PROCEDIMIENTO 1`),
         `ESPECIALIDAD TRATANTE`,
         `CIRUJANO TRATANTE`,
         ANESTESIOLOGO,
         `TIPO DE ANESTESIA`,
         CANCELACION,
         `CAUSA DE CANCELACION`,
         `TIEMPO EJECUTADO`,
         COMPLICACIONES,
         `TIPO DE COMPLICACION`,
         MORTALIDAD)

